[project]
name = "s3-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.37.21",
    "dotenv>=0.9.9",
    "mcp[cli]>=1.5.0",
]
